services:
  app:
    build: .
    ports:
      - "8080:8080"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - energy_net

  db:
    image: postgres:15-alpine
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - energy_net

networks:
  energy_net:
    driver: bridge

volumes:
  postgres_data:
